#!/bin/bash
# Create venv, install requirements, and run the Flask Spotify info server

python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
python get_spotify_info.py
