name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Backend
        run: |
          sudo cp "Pi files/get_spotify_info.py" /home/ewanritchie/spotipy_project/
          sudo systemctl restart spotify-flask

      - name: Deploy Frontend
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r ./* /var/www/html/
          sudo rm -rf "/var/www/html/Pi files"
          sudo rm -f /var/www/html/.gitignore /var/www/html/README.md

      - name: Reload Nginx
        run: sudo systemctl reload nginx